services:
  database:
    image: postgres:17.4
    command: postgres -c max_wal_size=6GB -c checkpoint_completion_target=0.9 -c synchronous_commit=off -c work_mem=512MB -c maintenance_work_mem=1024MB -c wal_buffers=128MB -c shared_buffers=1024MB

    volumes:
      - pg-db-data:/var/lib/postgresql/data
      #instead of copying files from a Dockerfile, do it using volumes
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password #FIXME change to a real password
    networks:
      - main
      # - isolated
    ports:
      - "5432:5432" #default for postgres
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U docker -d stm_server && pg_isready -U docker -d exo_server"]
          interval: 10s
          timeout: 10s
          retries: 5
          start_period: 60s

  setup-db:
    #TODO remove this pull_policy
    pull_policy: never
    build:
      context: .
      network: host
      dockerfile: Dockerfile.init
    network_mode: "host"
    volumes:
      - sqlite-local-data:/scripts/data/sqlite
      - extracted-data:/scripts/data/extracted
    depends_on:
      database:
        condition: service_healthy

  api:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    volumes:
      - sqlite-local-data:/app/data
    networks:
      # - isolated
      - main
    ports:
      - "${PORT}:80"
      #- "8001:443"
    profiles: ["api"]
    depends_on:
      database:
        condition: service_healthy
      setup-db:
        condition: service_completed_successfully

  #for ci/cd purposes, to verify sync between server and client code
  dev:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.dev
      args:
        - CLIENT_SCHEMA_FILE_PATH
    volumes:
      - sqlite-local-data:/script/data/
      - ${CLIENT_SCHEMA_FILE_PATH}/3.json:/script/data/file.json:ro
    profiles: ["dev"]
    depends_on:
      setup-db:
        condition: service_completed_successfully

volumes:
  pg-db-data:
  extracted-data: 
  sqlite-local-data:

networks:
  # isolated:
  #   name: isolated
  #   internal: true
  main:
    name: main
    driver: bridge
